# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='aes_encryption_key',
            field=models.CharField(default='$Z&)jWnAh1HdR!(fq77UZLqSLJ4ba0F7', editable=False, max_length=32),
        ),
    ]
