# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_control', '0003_auto_20180428_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='aes_encryption_key',
            field=models.CharField(default='PvA(qsMTJpgNBRcW1J(%oQxK!c^sPr3j', editable=False, max_length=32),
        ),
    ]
