# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_control', '0004_auto_20180428_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='aes_encryption_key',
            field=models.CharField(default='8@YW^EJmXZT5W*eo^i$fyKCdtMbSUjUI', editable=False, max_length=32),
        ),
    ]
