# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_control', '0004_auto_20180412_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='aes_encryption_key',
            field=models.CharField(default='tL6RDfsY)rV282i1&&vV9hJMpplQ76Qy', editable=False, max_length=32),
        ),
    ]
