# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_control', '0006_auto_20180428_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='aes_encryption_key',
            field=models.CharField(default='kX%Lyd&t%aH(2ky5fqw(Xfg86$YfOBIr', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='pwnedhost',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
