# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='aes_encryption_key',
            field=models.CharField(default='smWltAR1QM*uNKnjBt2dNLz&fymbwkXG', editable=False, max_length=32),
        ),
    ]
