# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_control', '0002_auto_20180408_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='aes_encryption_key',
            field=models.CharField(default='o0fE7xgKntE)Khbg2FQSewx$twHtFm3x', editable=False, max_length=32),
        ),
    ]
