# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_control', '0003_auto_20180408_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='aes_encryption_key',
            field=models.CharField(default='5s$AKK7*szOWusWnKy(cmN#!t9^&r0aV', editable=False, max_length=32),
        ),
    ]
